# db/scripts/env.dev.ps1

$env:PIXIE_ROOT         = "C:\Users\e\dev\pixie"
$env:PIXIE_PSQL_PATH    = "C:\Program Files\PostgreSQL\17\bin\psql.exe"

$env:PIXIE_DB_NAME      = "pixie-db-dev"
$env:PIXIE_DB_USER      = "postgres"
$env:PIXIE_DB_HOST      = "localhost"

$env:PIXIE_DB_SCHEMA    = "$env:PIXIE_ROOT\db\schema"
$env:PIXIE_DB_LOGS      = "$env:PIXIE_ROOT\db\logs"
$env:PIXIE_DB_ERRORS    = "$env:PIXIE_ROOT\db\errors"

Write-Host "Environment variables loaded:"
"PIXIE_ROOT         = $env:PIXIE_ROOT"
"PIXIE_PSQL_PATH    = $env:PIXIE_PSQL_PATH"
"PIXIE_DB_NAME      = $env:PIXIE_DB_NAME"
"PIXIE_DB_USER      = $env:PIXIE_DB_USER"
"PIXIE_DB_HOST      = $env:PIXIE_DB_HOST"
"PIXIE_DB_SCHEMA    = $env:PIXIE_DB_SCHEMA"
"PIXIE_DB_LOGS      = $env:PIXIE_DB_LOGS"
"PIXIE_DB_ERRORS    = $env:PIXIE_DB_ERRORS"
# SIG # Begin signature block
# MIIFcAYJKoZIhvcNAQcCoIIFYTCCBV0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUXhL1Ypp7NrVY5FTEcrw20xb2
# CeCgggMKMIIDBjCCAe6gAwIBAgIQQzKF37x4TZ1FLpXX31uI/zANBgkqhkiG9w0B
# AQsFADAbMRkwFwYDVQQDDBBEZXYgQ29kZSBTaWduaW5nMB4XDTI1MDYyNjEyMjU0
# NVoXDTI2MDYyNjEyNDU0NVowGzEZMBcGA1UEAwwQRGV2IENvZGUgU2lnbmluZzCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMGghZiagBDWRbuo9DOJ1inJ
# jENw5wIsjMIA2g27RkBp43QKWSQAnBS3+7z6JO6Afw0WrgKOaV7vEu4n2gAz9Ctl
# phjE+BsjRSifz2jTaDtEKQQsiOIWRQucdzM1tWcPV/H49Wvexo0RNKvjCoOsxaU1
# d2Ey0XoLxcn1kY+ABwALknG9PDDGXhRZfcRRXyZhfdOoSayDWtRqzSijsaRBuTOd
# iO6y5OpVKd7d2FQhv7h70PaOAkiytdZLCs+NhmiXFzsI83DPywVPOYGLzedg5mSC
# vPFEyqAKzvnEsutmBCy0LVkLAsWs+tqNrxzUONh9eXR5EfZETeHeEEP0tckz/iUC
# AwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0G
# A1UdDgQWBBS+W9K7Pf69ou3e01AR9lcc/QNpWzANBgkqhkiG9w0BAQsFAAOCAQEA
# OOpc2QSSXoE8BEF6NPeDly2I5yyLNkyRkq8EoCVB6tVIiVC/O5FbaPHdUR13wZj0
# 5/A5TTsMYBzbPVnDm1CMX28/FOGPse547dMGoa9/UlqmnuNnxYE24xHe/qsewocY
# kERh7/EIPx5L0n3TmF0A/hh5WsC4w2orrEvx/3AvhvK7hoI/GLg7+d9h5SASpIWQ
# 2pZm4NT1TA/7A83fMYdz9NbXfcO6tReheV91SbjdSF3KyMSOyDi6rbkhcK6OId7X
# jQQ67NT+BkoSjS3wtVt3tpMTL9zygNQFTprQYTYbGYRP8ofCqcJmr0A2IksmYHuU
# 7cUggjU9sWePKIg6b7VstjGCAdAwggHMAgEBMC8wGzEZMBcGA1UEAwwQRGV2IENv
# ZGUgU2lnbmluZwIQQzKF37x4TZ1FLpXX31uI/zAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUznw0
# 0dHnTcmeziL4FKRvYwKi+ScwDQYJKoZIhvcNAQEBBQAEggEAs4A6VWxFp4u3xw7X
# Qr/4bwwNwNutRHEipbsVudlyVv0NqUs1PkoatX7WHPvpn4DUqUjueRx5b/rhMzgA
# hEV0Fve2EXqsfx4nyEcles30O7q8o3d3jr8D0lgi3AGvK5BGU7uuv7doTiRMiSpI
# Y/4aSMa6Ld1Dozk8Cf3w2IlJjQImNa0kBxCvQW4i/U+eT15azz9OP4EqIkClOmiQ
# ntKp5zcG3/wXTIyaqnnt997HXLKJo9maKK+0dWnJLNCUwUX7h+grb85PprmBL6bI
# RD1Awm0R3MGmoc5XxJgub2JKVj6Zy/BlrvKJvZiGJ/Y/Z2Q8Y43Qv+CRVcq/vILf
# rPpazQ==
# SIG # End signature block
